services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: qazaqlinga_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      - DB_PROVIDER=mongo
    volumes:
      - uploads_data:/app/uploads
    ports:
      - "5000:5000"
    networks:
      - qazaqlinga_net

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5000
    container_name: qazaqlinga_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - qazaqlinga_net

volumes:
  uploads_data:

networks:
  qazaqlinga_net:
    driver: bridge